version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    environment:
      SERVER_HOST: localhost"
      SERVER_PORT: '8082'
    ports:
      - '8082:8082'
    restart: 'no'

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    environment:
      SERVER_HOST: "server"
      SERVER_PORT: '8082'
    restart: 'no'
    depends_on:
      - server

